-- Create Tickets table
CREATE TABLE IF NOT EXISTS Tickets (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    description TEXT,
    priority INTEGER NOT NULL CHECK(priority BETWEEN 1 AND 3),
    status TEXT NOT NULL DEFAULT 'OPEN',
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
);
